[tool.poetry]
name = "pkg-2"
version = "0.1.0"
description = "Second package in the repo"
authors = ["tejasrinivask <tejasrinivas@amagi.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
